apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jet-ingress
  namespace: jet-stream
spec:
  rules:
    - http:
        paths:
        {{ $replicas := .Values.replicaCount}}
        {{ $shards := .Values.shardCount}}
        {{ range $k, $v := until ( $shards | int) }}
        {{ range $k1, $v1 := until ( $replicas | int) }}
          - path: /jet/{{$k}}/{{$k1}}
            pathType: Prefix
            backend:
              service:
                name: jet-dir-{{$v}}-{{$v1}}
                port:
                  number: 8080
        {{ end }}
        {{end}}