{{ $replicas := .Values.replicaCount}}
{{ $shards := .Values.shardCount}}
{{ range $k, $v := until ( $shards | int) }}
{{ range $k1, $v1 := until ( $replicas | int) }}
---
apiVersion: v1
kind: Service
metadata:
  name: jet-dir-{{$v}}-{{$v1}}
  namespace: jet-stream
  annotations:
    cloud.google.com/app-protocols: '{"my-port":"HTTP2"}'
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: jet-shard-{{$v}}-{{$v1}}
  ports:
    - protocol: TCP
      name: my-port
      port: 8080
      targetPort: 8080
{{ end }}
{{end}}
