{{ $replicas := .Values.replicaCount}}
{{ $shards := .Values.shardCount}}
{{ $port := 8000}}
{{ range $k, $v := until ( $shards | int) }}
{{ range $k1, $v1 := until ( $replicas | int) }}
---
{{$port = add $port 1 }}
apiVersion: v1
kind: Service
metadata:
  name: jet-lb-{{$v}}-{{$v1}}
  namespace: jet-stream
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: jet-shard-{{$v}}-{{$v1}}
  ports:
    - protocol: TCP
      port: {{$port}}
      targetPort: 8080
{{ end }}
{{end}}