apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: jet-stream
  name: jet-volume
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/jet-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: jet-stream
  name: jet-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi