apiVersion: v1
kind: Service
metadata:
  name: jet-service
  namespace: jet-stream
  labels:
    app: jet
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: web
    - port: 8082
      targetPort: 8082
      name: health
    - port: 8081
      targetPort: 8081
      protocol: UDP
      name: gossip-udp
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: gossip-tcp
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: jet