apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: jet-gateway
  namespace: jet-stream
spec:
  gatewayClassName: jet-gateway-class
  listeners:
    - name: grpc
      protocol: HTTPS
      port: 8443
      tls:
        certificateRefs:
          - kind: Secret
            group: ""
            name: jet-certs