{{ $replicas := .Values.replicaCount}}
{{ $shards := .Values.shardCount}}
{{ range $k, $v := until ($shards| int) }}
{{ range $k1,$v1 := until ( $replicas | int)}}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GRPCRoute
metadata:
  name: jet-route-{{$k}}-{{$k1}}
  namespace: jet-stream
spec:
  parentRefs:
    - name: jet-gateway
  rules:
    - backendRefs:
        - name: jet-service-{{$k}}-{{$k1}}
          port: 8080
---
{{end}}
{{end}}